### ISSUE TITLE
Installation not possible on a debian 10 with python3.7 and pip V 20.1.1

### ISSUE THREAD

**Issue by skaysurfer** [tueit/it_management#106]
I cannot setup this nice app, errors:
frappe@vsrv99:~/frappe-bench$ bench get-app https://github.com/tueit/it_management.git
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

A directory for the application "it_management" already exists.
Do you want to continue and overwrite it? [y/N]: y

Getting it_management
$ git clone https://github.com/tueit/it_management.git  --depth 1 --origin upstream
Cloning into 'it_management'...
remote: Enumerating objects: 318, done.
remote: Counting objects: 100% (318/318), done.
remote: Compressing objects: 100% (120/120), done.
remote: Total 318 (delta 199), reused 308 (delta 193), pack-reused 0
Receiving objects: 100% (318/318), 149.02 KiB | 953.00 KiB/s, done.
Resolving deltas: 100% (199/199), done.

Installing it_management
$ ./env/bin/pip install -q -U -e ./apps/it_management
    ERROR: Command errored out with exit status 1:
     command: /home/frappe/frappe-bench/env/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/frappe/frappe-bench/apps/it_management/setup.py'"'"'; __file__='"'"'/home/frappe/frappe-bench/apps/it_management/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-vlbg6fcd
         cwd: /home/frappe/frappe-bench/apps/it_management/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/frappe/frappe-bench/apps/it_management/setup.py", line 28, in <module>
        install_requires=[str(ir.req) for ir in requirements],
      File "/home/frappe/frappe-bench/apps/it_management/setup.py", line 28, in <listcomp>
        install_requires=[str(ir.req) for ir in requirements],
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
$ bench build --app it_management
WARN: bench is installed in editable mode!

This is not the recommended mode of installation for production. Instead, install the package from PyPI with: `pip install frappe-bench`

Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/frappe/frappe-bench/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/frappe/frappe-bench/apps/frappe/frappe/commands/utils.py", line 24, in build
    frappe.init('')
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 174, in init
    setup_module_map()
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 999, in setup_module_map
    for module in get_module_list(app):
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 869, in get_module_list
    return get_file_items(os.path.join(os.path.dirname(get_module(app_name).__file__), "modules.txt"))
  File "/home/frappe/frappe-bench/apps/frappe/frappe/__init__.py", line 827, in get_module
    return importlib.import_module(modulename)
  File "/home/frappe/frappe-bench/env/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'it_management'

Please help.

**Comment by wojosc** [comment]
@musketeer90 do we know this error?

@skaysurfer we recommend installing on Ubuntu LTS versions. We have not tried the installation on Debian.

**Comment by musketeer90** [comment]
@skaysurfer I recommend installing it on Ubuntu, too. Have you installed ERPNexxt since the app depends on it

**Comment by skaysurfer** [comment]
yes, erpnext is installed and working.
i think there is something wrong in the setup.py of it_management.
I found a hint here: https://discuss.erpnext.com/t/pip-problems-workaround-by-yashodhan/40880 - but must be tested...

Ubuntu is Debian based, however maybe i will test another vm with ubuntu.

**Comment by musketeer90** [comment]
@skaysurfer I will push a change tonight. try it tomorrow, maybe i have a fix

**Comment by musketeer90** [comment]
@skaysurfer were you able to install it?

**Comment by skaysurfer** [comment]
@musketeer90 thank you, that works for me!
plus a downgrade of a component that was incompatible its now usable.

**Comment by wojosc** [comment]
Good to hear that. @skaysurfer if you need a quick introduciton, let us know. @musketeer90 I'm closing this issue.
