### ISSUE TITLE
Errors after install

### ISSUE THREAD

**Issue by skaysurfer** [tueit/it_management#74]
Hello,
i have just installed the it_management but get some errors:

erpnext@deb10:/srv/bench/erpnext$ bench --site erp.aytech.local install-app it_management

Installing it_management...
Updating DocTypes for it_management : [========================================]
Updating customizations for User Account
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/srv/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 97, in <module>
    main()
  File "/srv/bench/erpnext/apps/frappe/frappe/utils/bench_helper.py", line 18, in main
    click.Group(commands=commands)(prog_name='bench')
  File "/srv/bench/erpnext/env/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/srv/bench/erpnext/env/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/srv/bench/erpnext/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/bench/erpnext/env/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/srv/bench/erpnext/env/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/srv/bench/erpnext/env/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/srv/bench/erpnext/env/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/srv/bench/erpnext/apps/frappe/frappe/commands/__init__.py", line 25, in _func
    ret = f(frappe._dict(ctx.obj), *args, **kwargs)
  File "/srv/bench/erpnext/apps/frappe/frappe/commands/site.py", line 175, in install_app
    _install_app(app, verbose=context.verbose)
  File "/srv/bench/erpnext/apps/frappe/frappe/installer.py", line 97, in install_app
    sync_customizations(name)
  File "/srv/bench/erpnext/apps/frappe/frappe/modules/utils.py", line 96, in sync_customizations
    sync_customizations_for_doctype(data, folder)
  File "/srv/bench/erpnext/apps/frappe/frappe/modules/utils.py", line 152, in sync_customizations_for_doctype
    validate_fields_for_doctype(doctype)
  File "/srv/bench/erpnext/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 669, in validate_fields_for_doctype
    validate_fields(frappe.get_meta(doctype, cached=False))
  File "/srv/bench/erpnext/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 964, in validate_fields
    check_link_table_options(meta.get("name"), d)
  File "/srv/bench/erpnext/apps/frappe/frappe/core/doctype/doctype/doctype.py", line 728, in check_link_table_options
    frappe.throw(_("{0}: Options must be a valid DocType for field {1} in row {2}").format(docname, d.label, d.idx), WrongOptionsDoctypeLinkError)
  File "/srv/bench/erpnext/apps/frappe/frappe/__init__.py", line 382, in throw
    msgprint(msg, raise_exception=exc, title=title, indicator='red')
  File "/srv/bench/erpnext/apps/frappe/frappe/__init__.py", line 361, in msgprint
    _raise_exception()
  File "/srv/bench/erpnext/apps/frappe/frappe/__init__.py", line 315, in _raise_exception
    raise raise_exception(msg)
frappe.core.doctype.doctype.doctype.WrongOptionsDoctypeLinkError: User Account: Options must be a valid DocType for field Type in row 2
erpnext@deb10:/srv/bench/erpnext$

But i logged in to erpnext and have the Modul and try to use it.
Next i get an error when i try to save my first Solution:
pymysql.err.InternalError: (1054, "Unknown column 'tabIssue.dynamic_name' in 'where clause'")

My Innstalled Apps:
Installed Apps
ERPNext: v12.x.x-develop () (develop)
Frappe Framework: v12.x.x-develop () (develop)
IT Management: v0.0.1 (master)

Something is not set correct, but i dont know what - did i have to update my tables? If yes, where can i get the sql-update script?

am grateful for every tip

**Comment by wojosc** [comment]
Hi,
are you using debian as your base OS? We mostly use Ubuntu. I just talked to our developer who has also installed the app, he had no problem. Maybe @templis can help?

**Comment by templis** [comment]
do you have already done a bench migrate?

**Comment by wojosc** [comment]
Hi @skaysurfer I just installed the app on a test-system and ran into the same error as you. This is fixed with https://github.com/tueit/it_management/commit/4aabc878ede3a17204dd633d50b0dd745ff172ba

Thank you for testing the app. If you have any questions or inquiries do get back to us.

Regards
